name: Deploy to FTP

on:
    push:
        branches:
            - main

jobs:
    ftp-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: FTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USER }}
                  password: ${{ secrets.FTP_PASS }}
                  protocol: ftps-legacy
                  security: loose
                  port: ${{ secrets.FTP_PORT }}
                  local-dir: ./
                  server-dir: /www/
                  timeout: 190000
                  log-level: verbose
                  exclude: |
                      **/.git*
                      **/.git*/**
                      **/.github*
                      **/.github*/**
                      README.md
                      tailwind.config.js
